// The microcycle text pack as a Word document: the same content as the
// /pack/:blockId page (one heading per session, every line the TV board
// renders), written as plain paragraphs so a designer can copy and paste.
// Reads the LIVE documents through the store API on localhost:8127, the way
// the page does, so the two outputs can never disagree.
//
//   node scripts/pack-docx.mjs <blockId> <fromWeek> <toWeek> [out.docx]
//   node scripts/pack-docx.mjs str2-hyp 1 3 ../programming/x.docx
//
// A plain .txt with the same words is written beside the .docx.

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
  PageBreak,
  Footer,
  Header,
  BorderStyle,
} from 'docx';

import { FOCUS_CLASS_TYPE, FOCUS_DAY_PICK, FOCUS_LABEL } from '../src/lib/focusCatalog.ts';
import { DAY_NAMES } from '../src/lib/classDays.ts';
import { trainingWeekMonday } from '../src/lib/trainingWeeks.ts';
import { sessionLines } from '../src/lib/sessionText.ts';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const BASE = 'http://localhost:8127/api/store';
const argv = process.argv.slice(2);
// One session out of a week, by focus: `--focus full` writes the Saturday Full
// Body only. Without it every session in the week range is written.
const focusArg = (() => {
  const i = argv.findIndex((a) => a === '--focus' || a.startsWith('--focus='));
  if (i < 0) return null;
  const inline = argv[i].includes('=');
  const v = inline ? argv[i].split('=')[1] : argv[i + 1];
  argv.splice(i, inline ? 1 : 2);
  return v ?? null;
})();
// Board text only: the words the wall shows and nothing else. No session
// intent, no per-exercise notes or cues, no coach note, app description or
// footer blurb. This is what goes to the designer.
const boardOnly = (() => {
  const i = argv.indexOf('--board');
  if (i < 0) return false;
  argv.splice(i, 1);
  return true;
})();
const [blockId = 'str2-hyp', fromArg = '1', toArg = '', outArg = ''] = argv;

async function load(id) {
  const res = await fetch(`${BASE}/${id}`);
  if (!res.ok) throw new Error(`load ${id}: ${res.status}`);
  return (await res.json()).data;
}


const fmt = (d) => d.toLocaleDateString('en-AU', { day: 'numeric', month: 'long' });
const fmtY = (d) => d.toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' });

// ---------- load ----------
const [program, overrides, annual, schedule] = await Promise.all([
  load('program'), load('library-overrides'), load('annual-plan'), load('schedule'),
]);

// The footer blurb is generated by the app's own TypeScript (src/lib/blurb.ts).
// Run with `node --import ./scripts/ts-resolve.mjs` to load it straight from
// source; without the hook the blurb is left out and the run says so.
let generateBlurb = null;
let merged = [];
try {
  const [{ generateBlurb: gen }, { mergedLibrary }, { readFileSync }] = await Promise.all([
    import('../src/lib/blurb.ts'),
    import('../src/lib/library.ts'),
    import('node:fs'),
  ]);
  const base = JSON.parse(readFileSync(join(ROOT, 'public', 'data', 'exercise-library.json'), 'utf8'));
  merged = mergedLibrary(base, overrides);
  generateBlurb = gen;
} catch (err) {
  console.warn(`footer blurb left out (run with --import ./scripts/ts-resolve.mjs): ${String(err).split('\n')[0]}`);
}
let stream, block, bi, before = 0;
outer: for (const s of program.streams) {
  before = 0;
  for (let i = 0; i < s.blocks.length; i++) {
    if (s.blocks[i].id === blockId) { stream = s; block = s.blocks[i]; bi = i; break outer; }
    before += s.blocks[i].weeks.length;
  }
}
if (!block) throw new Error(`block ${blockId} not found`);
const from = Math.max(1, parseInt(fromArg, 10) || 1);
const to = Math.min(block.weeks.length, parseInt(toArg, 10) || block.weeks.length);
const breaks = annual.breaks ?? [];
const phase = annual.streams.find((l) => l.id === stream.id)?.phases.find((p) => p.id === block.annualPhaseId);
const cadence = stream.cadence ?? 'phases';
const phaseTitle = cadence === 'phases' ? `Phase ${bi + 1}` : (block.theme ?? '');
const blockLen = Math.max(1, block.blockLength ?? 4);
const micro = Math.floor((from - 1) / blockLen) + 1;
const microCount = Math.ceil(block.weeks.length / blockLen);
const windowTitle =
  from === to ? `Week ${from}`
    : (from - 1) % blockLen === 0 && to - from + 1 === blockLen ? `Microcycle ${micro} of ${microCount}`
    : `Weeks ${from} to ${to}`;
const live = schedule.scenarios.find((s) => s.id === schedule.liveScenarioId);
function dayFor(focus, monday) {
  const ct = FOCUS_CLASS_TYPE[focus];
  const days = [...new Set((live?.blocks ?? []).filter((b) => b.classTypeId === ct).map((b) => b.day))].sort((a, b) => a - b);
  const pick = focus in FOCUS_DAY_PICK ? FOCUS_DAY_PICK[focus] : 0;
  const idx = pick === null ? null : days[pick] ?? null;
  if (idx === null) return null;
  const d = new Date(monday); d.setDate(d.getDate() + idx);
  return { name: DAY_NAMES[idx], date: d };
}

// ---------- build: a flat list of {style, text} lines, then docx + txt ----------
const lines = [];
const L = (style, text) => lines.push({ style, text });

const weeks = block.weeks.slice(from - 1, to).map((week, i) => ({ week, wi: from - 1 + i, monday: trainingWeekMonday(annual.startDate, before + from - 1 + i, breaks) }));
const first = weeks[0].monday;
const last = new Date(weeks[weeks.length - 1].monday); last.setDate(last.getDate() + 6);

L('title', `${stream.name} ${phaseTitle} · ${windowTitle}`);
if (block.theme) L('subtitle', block.theme);
L('meta', `${fmtY(first)} to ${fmtY(last)} · ${weeks.length} weeks`);
if (!boardOnly) {
if (phase?.focus) L('body', phase.focus);
L('body', 'One section per session, in the order the classes run. Each carries every line the wall board shows: title, session intent, warm-up, each series with its minutes and how it is run, the numbered exercises with the prescription exactly as the board prints it, per-exercise notes, coaching cues and scaled options, then the coach note, the member app description and the footer blurb.');
L('body', `Teneriffe Athletic Club · 76 Commercial Road, Teneriffe · prepared ${fmtY(new Date())} · board text for design`);
}

for (const { week, wi, monday } of weeks) {
  for (const session of week.sessions) {
    if (focusArg && session.focus !== focusArg) continue;
    const title = (session.name ?? FOCUS_LABEL[session.focus]).toUpperCase();
    const day = dayFor(session.focus, monday);
    L('pagebreak', '');
    L('h1', boardOnly && day ? `${day.name} · ${title}` : `Week ${wi + 1} · ${title}`);
    L('meta', boardOnly
      ? `${phaseTitle} · Week ${wi + 1} of ${block.weeks.length}${day ? ` · ${day.name} ${fmtY(day.date)}` : ''}`
      : `${stream.name} · ${phaseTitle}${block.theme ? ` · ${block.theme}` : ''} · Week ${wi + 1} of ${block.weeks.length}${day ? ` · ${day.name} ${fmt(day.date)}` : ''}`);
    if (session.intent && !boardOnly) { L('label', 'Session intent'); L('quote', session.intent); }
    // What the session says is decided once, in src/lib/sessionText.ts. This
    // file only chooses how it is drawn. The intent is handled above, as a
    // pull quote, so it is asked for separately.
    const blurb = boardOnly
      ? ''
      : session.blurbOverride ??
        (generateBlurb && session.kind !== 'circuit' ? generateBlurb(session, merged, overrides) : '');
    const body = sessionLines(session, overrides, {
      boardOnly,
      upperHeadings: false,
      blankLines: false,
      includeIntent: false,
      blurb,
    });
    if (!body.length) L('body', 'Not written yet.');
    const STYLE = { heading: 'h2', note: 'note', exercise: 'exercise', detail: 'detail', sub: 'sub', label: 'label', body: 'body' };
    for (const line of body) {
      if (line.style === 'blank') continue;
      L(STYLE[line.style] ?? 'body', line.text);
    }
  }
}

// ---------- write .txt ----------
const outDocx = resolve(outArg || join(ROOT, '..', 'programming', `TAC-${stream.id}-${block.id}-w${from}-${to}-board-text.docx`));
const outTxt = outDocx.replace(/\.docx$/i, '.txt');
const txt = lines.map(({ style, text }) => {
  switch (style) {
    case 'pagebreak': return '\n\n' + '='.repeat(72);
    case 'title': return text.toUpperCase();
    case 'h1': return '\n' + text.toUpperCase();
    case 'h2': return '\n' + text;
    case 'exercise': return '  ' + text;
    case 'detail': return '      ' + text;
    case 'sub': return '      ' + text;
    case 'label': return '\n' + text.toUpperCase();
    default: return text;
  }
}).join('\n');
writeFileSync(outTxt, txt + '\n', 'utf8');

// ---------- write .docx ----------
const PINE = '003030';
const SAND = 'DEC5AE';
const run = (text, o = {}) => new TextRun({ text, font: o.font ?? 'Mulish', size: o.size ?? 21, bold: o.bold, italics: o.italics, color: o.color, ...o });
const para = (children, o = {}) => new Paragraph({ children: Array.isArray(children) ? children : [children], ...o });
const children = [];
for (const { style, text } of lines) {
  switch (style) {
    case 'pagebreak': children.push(new Paragraph({ children: [new PageBreak()] })); break;
    case 'title': children.push(para(run(text, { font: 'Fraunces', size: 48, color: '201D1D' }), { heading: HeadingLevel.TITLE, spacing: { after: 120 } })); break;
    case 'subtitle': children.push(para(run(text, { size: 28, bold: true, color: PINE }), { spacing: { after: 80 } })); break;
    case 'meta': children.push(para(run(text, { size: 19, bold: true, color: PINE }), { spacing: { after: 160 } })); break;
    case 'h1': children.push(para(run(text, { font: 'Fraunces', size: 40, color: '201D1D' }), { heading: HeadingLevel.HEADING_1, spacing: { before: 0, after: 60 }, border: { bottom: { style: BorderStyle.SINGLE, size: 12, color: PINE, space: 4 } } })); break;
    case 'h2': children.push(para(run(text, { size: 24, bold: true, color: PINE }), { heading: HeadingLevel.HEADING_2, spacing: { before: 240, after: 80 }, border: { bottom: { style: BorderStyle.SINGLE, size: 8, color: SAND, space: 2 } } })); break;
    case 'label': children.push(para(run(text.toUpperCase(), { size: 15, bold: true, color: PINE, characterSpacing: 40 }), { spacing: { before: 200, after: 40 } })); break;
    case 'quote': children.push(para(run(text, { font: 'Fraunces', size: 23, italics: true }), { indent: { left: 240 }, border: { left: { style: BorderStyle.SINGLE, size: 18, color: SAND, space: 8 } }, spacing: { after: 120 } })); break;
    case 'note': children.push(para(run(text, { size: 20, bold: true, color: PINE }), { spacing: { after: 80 } })); break;
    case 'exercise': children.push(para(run(text, { size: 22, bold: true }), { spacing: { before: 100, after: 20 }, keepNext: true })); break;
    case 'detail': children.push(para(run(text, { size: 20, bold: true, color: PINE }), { indent: { left: 360 }, spacing: { after: 20 } })); break;
    case 'sub': children.push(para(run(text, { size: 18, color: '5A5654' }), { indent: { left: 360 }, spacing: { after: 20 } })); break;
    default: children.push(para(run(text), { spacing: { after: 100 } }));
  }
}
const doc = new Document({
  creator: 'TAC coaching tool',
  title: `${stream.name} ${phaseTitle} · ${windowTitle} · board text`,
  styles: { default: { document: { run: { font: 'Mulish', size: 21 } } } },
  sections: [{
    properties: { page: { size: { width: 11906, height: 16838 }, margin: { top: 1134, right: 1134, bottom: 1134, left: 1134 } } },
    headers: { default: new Header({ children: [para(run(`TENERIFFE ATHLETIC CLUB · ${stream.name.toUpperCase()} · ${phaseTitle.toUpperCase()} · ${windowTitle.toUpperCase()}`, { size: 14, bold: true, color: PINE, characterSpacing: 60 }))] }) },
    footers: { default: new Footer({ children: [para(run('Board text as the coaching tool renders it. Nothing here is published to members. · 76 Commercial Road, Teneriffe', { size: 14, color: '7A7674' }), { alignment: AlignmentType.CENTER })] }) },
    children,
  }],
});
writeFileSync(outDocx, await Packer.toBuffer(doc));
console.log(`${lines.length} lines · ${outDocx}\n${outTxt}`);
